// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="DocumentApiTests.cs">
//   Copyright (c) 2018 Aspose.Slides for Cloud
// </copyright>
// <summary>
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Aspose.Slides.Cloud.Sdk.Model;
using Aspose.Slides.Cloud.Sdk.Model.Requests;

using Aspose.Slides.Cloud.Sdk.Tests.Utils;

namespace Aspose.Slides.Cloud.Sdk.Tests
{
    /// <summary>
    ///  Class for testing DocumentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DocumentApiTests
    {
        private DocumentApi m_instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            m_instance = new DocumentApi(TestUtils.Configuration);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        
        /// <summary>
        /// Test GetSlidesApiInfo
        /// </summary>
        [Test]
        public void GetSlidesApiInfo()
        {
            TestExecutor<GetSlidesApiInfoRequest, ApiInfoResponse> testExecutor =
                new TestExecutor<GetSlidesApiInfoRequest, ApiInfoResponse>("GetSlidesApiInfo", null);
            GetSlidesApiInfoRequest request = testExecutor.PrepareRequest();
            ApiInfoResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesApiInfo(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesDocument
        /// </summary>
        [Test]
        public void GetSlidesDocument()
        {
            TestExecutor<GetSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<GetSlidesDocumentRequest, DocumentResponse>("GetSlidesDocument", null);
            GetSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentInvalidName()
        {
            TestExecutor<GetSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<GetSlidesDocumentRequest, DocumentResponse>("GetSlidesDocument", "Name");
            GetSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentInvalidPassword()
        {
            TestExecutor<GetSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<GetSlidesDocumentRequest, DocumentResponse>("GetSlidesDocument", "Password");
            GetSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentInvalidStorage()
        {
            TestExecutor<GetSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<GetSlidesDocumentRequest, DocumentResponse>("GetSlidesDocument", "Storage");
            GetSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentInvalidFolder()
        {
            TestExecutor<GetSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<GetSlidesDocumentRequest, DocumentResponse>("GetSlidesDocument", "Folder");
            GetSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesDocumentWithFormat
        /// </summary>
        [Test]
        public void GetSlidesDocumentWithFormat()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", null);
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidName()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "Name");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidFormat()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "Format");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidJpegQuality()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "JpegQuality");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidPassword()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "Password");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidStorage()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "Storage");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidFolder()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "Folder");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidOutPath()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "OutPath");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesDocumentWithFormatInvalidFontsFolder()
        {
            TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesDocumentWithFormatRequest, System.IO.Stream>("GetSlidesDocumentWithFormat", "FontsFolder");
            GetSlidesDocumentWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesDocumentWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PostSlidesDocument
        /// </summary>
        [Test]
        public void PostSlidesDocument()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", null);
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidName()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "Name");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidData()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "Data");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidTemplatePath()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "TemplatePath");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidTemplateStorage()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "TemplateStorage");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidIsImageDataEmbedded()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "IsImageDataEmbedded");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidPassword()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "Password");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidStorage()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "Storage");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesDocumentInvalidFolder()
        {
            TestExecutor<PostSlidesDocumentRequest, DocumentResponse> testExecutor =
                new TestExecutor<PostSlidesDocumentRequest, DocumentResponse>("PostSlidesDocument", "Folder");
            PostSlidesDocumentRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesDocument(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PostSlidesPipeline
        /// </summary>
        [Test]
        public void PostSlidesPipeline()
        {
            TestExecutor<PostSlidesPipelineRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesPipelineRequest, System.IO.Stream>("PostSlidesPipeline", null);
            PostSlidesPipelineRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesPipeline(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesPipelineInvalidPipeline()
        {
            TestExecutor<PostSlidesPipelineRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesPipelineRequest, System.IO.Stream>("PostSlidesPipeline", "Pipeline");
            PostSlidesPipelineRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesPipeline(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PostSlidesSaveAs
        /// </summary>
        [Test]
        public void PostSlidesSaveAs()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", null);
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidName()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "Name");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidFormat()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "Format");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidOptions()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "Options");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidPassword()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "Password");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidStorage()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "Storage");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidFolder()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "Folder");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidOutPath()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "OutPath");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSaveAsInvalidFontsFolder()
        {
            TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PostSlidesSaveAsRequest, System.IO.Stream>("PostSlidesSaveAs", "FontsFolder");
            PostSlidesSaveAsRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSaveAs(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PostSlidesSplit
        /// </summary>
        [Test]
        public void PostSlidesSplit()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", null);
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidName()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Name");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidOptions()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Options");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidFormat()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Format");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidWidth()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Width");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidHeight()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Height");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidTo()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "To");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidFrom()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "From");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidDestFolder()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "DestFolder");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidPassword()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Password");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidStorage()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Storage");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PostSlidesSplitInvalidFolder()
        {
            TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse> testExecutor =
                new TestExecutor<PostSlidesSplitRequest, SplitDocumentResponse>("PostSlidesSplit", "Folder");
            PostSlidesSplitRequest request = testExecutor.PrepareRequest();
            SplitDocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PostSlidesSplit(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PutNewPresentation
        /// </summary>
        [Test]
        public void PutNewPresentation()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", null);
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidName()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "Name");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidStream()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "Stream");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidTemplatePath()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "TemplatePath");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidTemplatePassword()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "TemplatePassword");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidTemplateStorage()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "TemplateStorage");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidPassword()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "Password");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidStorage()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "Storage");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutNewPresentationInvalidFolder()
        {
            TestExecutor<PutNewPresentationRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutNewPresentationRequest, DocumentResponse>("PutNewPresentation", "Folder");
            PutNewPresentationRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutNewPresentation(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PutSlidesConvert
        /// </summary>
        [Test]
        public void PutSlidesConvert()
        {
            TestExecutor<PutSlidesConvertRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PutSlidesConvertRequest, System.IO.Stream>("PutSlidesConvert", null);
            PutSlidesConvertRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesConvert(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesConvertInvalidFormat()
        {
            TestExecutor<PutSlidesConvertRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PutSlidesConvertRequest, System.IO.Stream>("PutSlidesConvert", "Format");
            PutSlidesConvertRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesConvert(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesConvertInvalidDocument()
        {
            TestExecutor<PutSlidesConvertRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PutSlidesConvertRequest, System.IO.Stream>("PutSlidesConvert", "Document");
            PutSlidesConvertRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesConvert(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesConvertInvalidPassword()
        {
            TestExecutor<PutSlidesConvertRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PutSlidesConvertRequest, System.IO.Stream>("PutSlidesConvert", "Password");
            PutSlidesConvertRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesConvert(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesConvertInvalidOutPath()
        {
            TestExecutor<PutSlidesConvertRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PutSlidesConvertRequest, System.IO.Stream>("PutSlidesConvert", "OutPath");
            PutSlidesConvertRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesConvert(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesConvertInvalidFontsFolder()
        {
            TestExecutor<PutSlidesConvertRequest, System.IO.Stream> testExecutor =
                new TestExecutor<PutSlidesConvertRequest, System.IO.Stream>("PutSlidesConvert", "FontsFolder");
            PutSlidesConvertRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesConvert(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PutSlidesDocumentFromHtml
        /// </summary>
        [Test]
        public void PutSlidesDocumentFromHtml()
        {
            TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse>("PutSlidesDocumentFromHtml", null);
            PutSlidesDocumentFromHtmlRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesDocumentFromHtml(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesDocumentFromHtmlInvalidName()
        {
            TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse>("PutSlidesDocumentFromHtml", "Name");
            PutSlidesDocumentFromHtmlRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesDocumentFromHtml(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesDocumentFromHtmlInvalidHtml()
        {
            TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse>("PutSlidesDocumentFromHtml", "Html");
            PutSlidesDocumentFromHtmlRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesDocumentFromHtml(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesDocumentFromHtmlInvalidPassword()
        {
            TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse>("PutSlidesDocumentFromHtml", "Password");
            PutSlidesDocumentFromHtmlRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesDocumentFromHtml(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesDocumentFromHtmlInvalidStorage()
        {
            TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse>("PutSlidesDocumentFromHtml", "Storage");
            PutSlidesDocumentFromHtmlRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesDocumentFromHtml(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesDocumentFromHtmlInvalidFolder()
        {
            TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesDocumentFromHtmlRequest, DocumentResponse>("PutSlidesDocumentFromHtml", "Folder");
            PutSlidesDocumentFromHtmlRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesDocumentFromHtml(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test PutSlidesSlideSize
        /// </summary>
        [Test]
        public void PutSlidesSlideSize()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", null);
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidName()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "Name");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidPassword()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "Password");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidStorage()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "Storage");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidFolder()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "Folder");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidWidth()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "Width");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidHeight()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "Height");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidSizeType()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "SizeType");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void PutSlidesSlideSizeInvalidScaleType()
        {
            TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse> testExecutor =
                new TestExecutor<PutSlidesSlideSizeRequest, DocumentResponse>("PutSlidesSlideSize", "ScaleType");
            PutSlidesSlideSizeRequest request = testExecutor.PrepareRequest();
            DocumentResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.PutSlidesSlideSize(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
    }
}
