// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="ImagesApiTests.cs">
//   Copyright (c) 2018 Aspose.Slides for Cloud
// </copyright>
// <summary>
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Aspose.Slides.Cloud.Sdk.Model;
using Aspose.Slides.Cloud.Sdk.Model.Requests;

using Aspose.Slides.Cloud.Sdk.Tests.Utils;

namespace Aspose.Slides.Cloud.Sdk.Tests
{
    /// <summary>
    ///  Class for testing ImagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ImagesApiTests
    {
        private ImagesApi m_instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            m_instance = new ImagesApi(TestUtils.Configuration);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        
        /// <summary>
        /// Test GetSlidesImageWithFormat
        /// </summary>
        [Test]
        public void GetSlidesImageWithFormat()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", null);
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImageWithFormatInvalidName()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", "Name");
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImageWithFormatInvalidIndex()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", "Index");
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImageWithFormatInvalidFormat()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", "Format");
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImageWithFormatInvalidPassword()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", "Password");
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImageWithFormatInvalidFolder()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", "Folder");
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImageWithFormatInvalidStorage()
        {
            TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream> testExecutor =
                new TestExecutor<GetSlidesImageWithFormatRequest, System.IO.Stream>("GetSlidesImageWithFormat", "Storage");
            GetSlidesImageWithFormatRequest request = testExecutor.PrepareRequest();
            System.IO.Stream response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImageWithFormat(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesImages
        /// </summary>
        [Test]
        public void GetSlidesImages()
        {
            TestExecutor<GetSlidesImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesImagesRequest, ImagesResponse>("GetSlidesImages", null);
            GetSlidesImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImagesInvalidName()
        {
            TestExecutor<GetSlidesImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesImagesRequest, ImagesResponse>("GetSlidesImages", "Name");
            GetSlidesImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImagesInvalidPassword()
        {
            TestExecutor<GetSlidesImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesImagesRequest, ImagesResponse>("GetSlidesImages", "Password");
            GetSlidesImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImagesInvalidFolder()
        {
            TestExecutor<GetSlidesImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesImagesRequest, ImagesResponse>("GetSlidesImages", "Folder");
            GetSlidesImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesImagesInvalidStorage()
        {
            TestExecutor<GetSlidesImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesImagesRequest, ImagesResponse>("GetSlidesImages", "Storage");
            GetSlidesImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesSlideImages
        /// </summary>
        [Test]
        public void GetSlidesSlideImages()
        {
            TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse>("GetSlidesSlideImages", null);
            GetSlidesSlideImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesSlideImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesSlideImagesInvalidName()
        {
            TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse>("GetSlidesSlideImages", "Name");
            GetSlidesSlideImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesSlideImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesSlideImagesInvalidSlideIndex()
        {
            TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse>("GetSlidesSlideImages", "SlideIndex");
            GetSlidesSlideImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesSlideImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesSlideImagesInvalidPassword()
        {
            TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse>("GetSlidesSlideImages", "Password");
            GetSlidesSlideImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesSlideImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesSlideImagesInvalidFolder()
        {
            TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse>("GetSlidesSlideImages", "Folder");
            GetSlidesSlideImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesSlideImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesSlideImagesInvalidStorage()
        {
            TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse> testExecutor =
                new TestExecutor<GetSlidesSlideImagesRequest, ImagesResponse>("GetSlidesSlideImages", "Storage");
            GetSlidesSlideImagesRequest request = testExecutor.PrepareRequest();
            ImagesResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesSlideImages(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
    }
}
