// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="ThemeApiTests.cs">
//   Copyright (c) 2018 Aspose.Slides for Cloud
// </copyright>
// <summary>
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Aspose.Slides.Cloud.Sdk.Model;
using Aspose.Slides.Cloud.Sdk.Model.Requests;

using Aspose.Slides.Cloud.Sdk.Tests.Utils;

namespace Aspose.Slides.Cloud.Sdk.Tests
{
    /// <summary>
    ///  Class for testing ThemeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ThemeApiTests
    {
        private ThemeApi m_instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            m_instance = new ThemeApi(TestUtils.Configuration);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
        }

        
        /// <summary>
        /// Test GetSlidesTheme
        /// </summary>
        [Test]
        public void GetSlidesTheme()
        {
            GeneralTestExecutor<GetSlidesThemeRequest, ThemeResponse> testExecutor =
                new GeneralTestExecutor<GetSlidesThemeRequest, ThemeResponse>("GetSlidesTheme");
            GetSlidesThemeRequest request = testExecutor.PrepareRequest();
            ThemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesTheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeInvalidName()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse>("GetSlidesTheme", "Name");
            GetSlidesThemeRequest request = testExecutor.PrepareRequest();
            ThemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesTheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeInvalidSlideIndex()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse>("GetSlidesTheme", "SlideIndex");
            GetSlidesThemeRequest request = testExecutor.PrepareRequest();
            ThemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesTheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeInvalidPassword()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse>("GetSlidesTheme", "Password");
            GetSlidesThemeRequest request = testExecutor.PrepareRequest();
            ThemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesTheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeInvalidFolder()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse>("GetSlidesTheme", "Folder");
            GetSlidesThemeRequest request = testExecutor.PrepareRequest();
            ThemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesTheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeInvalidStorage()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeRequest, ThemeResponse>("GetSlidesTheme", "Storage");
            GetSlidesThemeRequest request = testExecutor.PrepareRequest();
            ThemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesTheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesThemeColorScheme
        /// </summary>
        [Test]
        public void GetSlidesThemeColorScheme()
        {
            GeneralTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse> testExecutor =
                new GeneralTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse>("GetSlidesThemeColorScheme");
            GetSlidesThemeColorSchemeRequest request = testExecutor.PrepareRequest();
            ColorSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeColorScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeColorSchemeInvalidName()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse>("GetSlidesThemeColorScheme", "Name");
            GetSlidesThemeColorSchemeRequest request = testExecutor.PrepareRequest();
            ColorSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeColorScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeColorSchemeInvalidSlideIndex()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse>("GetSlidesThemeColorScheme", "SlideIndex");
            GetSlidesThemeColorSchemeRequest request = testExecutor.PrepareRequest();
            ColorSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeColorScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeColorSchemeInvalidPassword()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse>("GetSlidesThemeColorScheme", "Password");
            GetSlidesThemeColorSchemeRequest request = testExecutor.PrepareRequest();
            ColorSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeColorScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeColorSchemeInvalidFolder()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse>("GetSlidesThemeColorScheme", "Folder");
            GetSlidesThemeColorSchemeRequest request = testExecutor.PrepareRequest();
            ColorSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeColorScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeColorSchemeInvalidStorage()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeColorSchemeRequest, ColorSchemeResponse>("GetSlidesThemeColorScheme", "Storage");
            GetSlidesThemeColorSchemeRequest request = testExecutor.PrepareRequest();
            ColorSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeColorScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesThemeFontScheme
        /// </summary>
        [Test]
        public void GetSlidesThemeFontScheme()
        {
            GeneralTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse> testExecutor =
                new GeneralTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse>("GetSlidesThemeFontScheme");
            GetSlidesThemeFontSchemeRequest request = testExecutor.PrepareRequest();
            FontSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFontScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFontSchemeInvalidName()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse>("GetSlidesThemeFontScheme", "Name");
            GetSlidesThemeFontSchemeRequest request = testExecutor.PrepareRequest();
            FontSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFontScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFontSchemeInvalidSlideIndex()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse>("GetSlidesThemeFontScheme", "SlideIndex");
            GetSlidesThemeFontSchemeRequest request = testExecutor.PrepareRequest();
            FontSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFontScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFontSchemeInvalidPassword()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse>("GetSlidesThemeFontScheme", "Password");
            GetSlidesThemeFontSchemeRequest request = testExecutor.PrepareRequest();
            FontSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFontScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFontSchemeInvalidFolder()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse>("GetSlidesThemeFontScheme", "Folder");
            GetSlidesThemeFontSchemeRequest request = testExecutor.PrepareRequest();
            FontSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFontScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFontSchemeInvalidStorage()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFontSchemeRequest, FontSchemeResponse>("GetSlidesThemeFontScheme", "Storage");
            GetSlidesThemeFontSchemeRequest request = testExecutor.PrepareRequest();
            FontSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFontScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
        /// <summary>
        /// Test GetSlidesThemeFormatScheme
        /// </summary>
        [Test]
        public void GetSlidesThemeFormatScheme()
        {
            GeneralTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse> testExecutor =
                new GeneralTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse>("GetSlidesThemeFormatScheme");
            GetSlidesThemeFormatSchemeRequest request = testExecutor.PrepareRequest();
            FormatSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFormatScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFormatSchemeInvalidName()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse>("GetSlidesThemeFormatScheme", "Name");
            GetSlidesThemeFormatSchemeRequest request = testExecutor.PrepareRequest();
            FormatSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFormatScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFormatSchemeInvalidSlideIndex()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse>("GetSlidesThemeFormatScheme", "SlideIndex");
            GetSlidesThemeFormatSchemeRequest request = testExecutor.PrepareRequest();
            FormatSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFormatScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFormatSchemeInvalidPassword()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse>("GetSlidesThemeFormatScheme", "Password");
            GetSlidesThemeFormatSchemeRequest request = testExecutor.PrepareRequest();
            FormatSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFormatScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFormatSchemeInvalidFolder()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse>("GetSlidesThemeFormatScheme", "Folder");
            GetSlidesThemeFormatSchemeRequest request = testExecutor.PrepareRequest();
            FormatSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFormatScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        [Test]
        public void GetSlidesThemeFormatSchemeInvalidStorage()
        {
            InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse> testExecutor =
                new InvalidPropertyTestExecutor<GetSlidesThemeFormatSchemeRequest, FormatSchemeResponse>("GetSlidesThemeFormatScheme", "Storage");
            GetSlidesThemeFormatSchemeRequest request = testExecutor.PrepareRequest();
            FormatSchemeResponse response = null;
            bool needAssertResponse = false;
            try
            {
                response = m_instance.GetSlidesThemeFormatScheme(request);
                needAssertResponse = true;
            }
            catch (Exception ex)
            {
                testExecutor.AssertException(ex);
            }
            if (needAssertResponse)
            {
                testExecutor.AssertResult(response);
            }
        }

        
    }
}
